* X, Y ~ Ben(0.5) 
* Decide m, which is the number of rows such that m  < n * H(Z) where H(Z) = h(p) 
* h(p) = -plog(2)p-(1-p)log(2)(1-p)
* p < 0.5 eller 0.1
* m ≈ nh(p)

In [2]:
import math
import random
import numpy as np
from scipy.stats import entropy

In [3]:
def generate_bernoulli_vectors(n):
    x = [random.choice([0, 1]) for _ in range(n)]
    y = [random.choice([0, 1]) for _ in range(n)]
    return x, y

In [4]:
def modulo_two_sum(x, y):
    return [((x[i] + y[i]) % 2) for i in range(len(x))]

In [5]:
def generate_matrix(m, n):
    matrix = np.random.binomial(n=1, p=0.5, size=(m, n))
    return matrix

In [6]:
def calc_entropy(p):
    h_p = -p*math.log2(p) - (1-p)*math.log2(1-p)
    return h_p

In [40]:
n = 15 
#random.randint(10, 20)
print("Vectors of length n:",n, "\n")

D = np.random.binomial(1, 0.1, n)

#X, Y = generate_bernoulli_vectors(n)
#print("X:", X)
#print("Y:", Y, "\n")

hp = calc_entropy(0.1)
nhp= n*hp
print("h(p): ",hp)
print("nh(p): ",nhp, "\n")

A = generate_matrix(math.floor(nhp), n)
print("Matrix A:", A.shape, "\n")
print(A, "\n")

AD = np.dot(A, D)
#print("AD:",AD, "\n")

#AY = np.dot(A, Y)
#print("AY:",AY, "\n")

#Z = modulo_two_sum(X, Y)
#print ("Z: ", Z, "\n")

#AZ = modulo_two_sum(AX, AY)
#print("AZ:", AZ, "\n" )

res = AD % 2
print("AD % 2: \n", res)

Vectors of length n: 15 

h(p):  0.4689955935892812
nh(p):  7.034933903839218 

Matrix A: (7, 15) 

[[0 1 0 1 0 0 1 0 0 0 0 0 1 0 1]
 [1 1 0 1 0 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 0 0 1 1 1 0 0 1 1 0 0 0]
 [0 1 0 1 1 1 0 1 0 1 1 1 0 1 1]
 [0 1 0 1 1 1 1 1 1 0 0 1 1 1 0]
 [1 0 1 1 1 0 0 1 0 1 1 0 1 1 0]
 [1 1 0 0 0 1 1 0 1 0 0 1 0 0 1]] 

AD % 2: 
 [1 0 1 1 0 0 1]


In [39]:
pseudo_inverse = np.linalg.pinv(A)
print("pseudo_inverse \n", pseudo_inverse, "\n")
r = np.dot(A, pseudo_inverse)
print(r, "\n")

m = np.dot(pseudo_inverse, res)
print(m, "\n")

print(D)


pseudo_inverse 
 [[ 9.42350333e-02 -8.60310421e-02  4.21286031e-03 -2.23946785e-02
  -1.21951220e-01 -1.00221729e-01  2.22616408e-01]
 [-3.43680710e-02  1.01995565e-02 -2.55654102e-01  2.01108647e-01
  -7.31707317e-02  1.87139690e-01 -8.82483370e-02]
 [ 7.76053215e-03  2.23503326e-01 -2.32594235e-01  3.41685144e-01
   4.87804878e-02 -2.03547672e-01 -2.38137472e-01]
 [ 1.74057650e-01  1.28603104e-02  6.89578714e-02 -5.07760532e-02
  -4.87804878e-02  1.49002217e-01 -1.98226164e-01]
 [ 9.20177384e-02 -1.49889135e-01  2.13525499e-01  2.28381375e-02
   2.92682927e-01 -1.84922395e-01 -1.37915743e-01]
 [ 2.32815965e-02  7.05099778e-02  1.02217295e-01 -1.74944568e-01
   1.46341463e-01 -1.06430155e-02  8.55875831e-02]
 [-1.35254989e-01 -2.95343681e-01 -3.19290466e-02 -4.07982262e-02
   2.92682927e-01  2.33259424e-01  2.07538803e-01]
 [-1.10864745e-02  8.07095344e-02 -1.53436807e-01  2.61640798e-02
   7.31707317e-02  1.76496674e-01 -2.66075388e-03]
 [ 1.74057650e-01  1.28603104e-02  6.89578714e-