* X, Y ~ Ben(0.5) 
* Decide m, which is the number of rows such that m  < n * H(Z) where H(Z) = h(p) 
* h(p) = -plog(2)p-(1-p)log(2)(1-p)
* p < 0.5 eller 0.1
* m ≈ nh(p)

In [1]:
import math
import random
import numpy as np
from scipy.stats import entropy

In [2]:
def generate_bernoulli_vectors(n):
    x = [random.choice([0, 1]) for _ in range(n)]
    y = [random.choice([0, 1]) for _ in range(n)]
    return x, y

In [3]:
def modulo_two_sum(x, y):
    return [((x[i] + y[i]) % 2) for i in range(len(x))]

In [4]:
def generate_matrix(m, n):
    matrix = np.random.binomial(n=1, p=0.5, size=(m, n))
    return matrix

In [5]:
def calc_entropy(p):
    h_p = -p*math.log2(p) - (1-p)*math.log2(1-p)
    return h_p

In [6]:
n = 10
X, Y = generate_bernoulli_vectors(n)
print("X: ", X)
print("Y: ", Y, "\n")

A = generate_matrix(4, n)
print("Matrix A: \n", A, "\n")

h_p = calc_entropy(0.1)
print("h(p): ",h_p)
print("nh(p): ",n*h_p)

X:  [0, 0, 1, 0, 0, 0, 0, 1, 0, 1]
Y:  [0, 1, 1, 1, 0, 0, 1, 1, 1, 1] 

Matrix A: 
 [[0 0 1 1 1 0 1 1 0 1]
 [1 1 0 0 1 0 1 1 1 1]
 [1 0 0 1 1 1 1 0 1 0]
 [1 0 1 0 1 1 1 1 0 0]] 

h(p):  0.4689955935892812
nh(p):  4.6899559358928125


In [7]:
AX = np.dot(A, X)
print("AX: ",AX, "\n")

AY = np.dot(A, Y)
print("AY: ",AY, "\n")

Z = modulo_two_sum(X, Y)
print ("Z: ", Z, "\n")

AZ = modulo_two_sum(AX, AY)
print("AZ: ", AZ, )

AX:  [3 2 0 2] 

AY:  [5 5 3 3] 

Z:  [0, 1, 0, 1, 0, 0, 1, 0, 1, 0] 

AZ:  [0, 1, 1, 1]
